[package]
name = "read-excel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.21.2"
csv = "1.2.2"
serde_json = "1.0.103"
xlsxwriter = "0.6.0"
